// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmNEF1EkoNfGIO0C1nu927YQDFEmXo8u4',
    appId: '1:626777238610:web:5d3506923f6659b08e038b',
    messagingSenderId: '626777238610',
    projectId: 'dailydocket-84053',
    authDomain: 'dailydocket-84053.firebaseapp.com',
    storageBucket: 'dailydocket-84053.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnMPaOTxCYU_psYYvu77WkZpTqtOEMJk4',
    appId: '1:626777238610:android:bb14a4e180a6fc928e038b',
    messagingSenderId: '626777238610',
    projectId: 'dailydocket-84053',
    storageBucket: 'dailydocket-84053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfVVVIQb488Tq9sHv2PCGIQWraj3gzdYE',
    appId: '1:626777238610:ios:f9c6492c5147f3da8e038b',
    messagingSenderId: '626777238610',
    projectId: 'dailydocket-84053',
    storageBucket: 'dailydocket-84053.appspot.com',
    iosBundleId: 'com.example.dailyDocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfVVVIQb488Tq9sHv2PCGIQWraj3gzdYE',
    appId: '1:626777238610:ios:f9c6492c5147f3da8e038b',
    messagingSenderId: '626777238610',
    projectId: 'dailydocket-84053',
    storageBucket: 'dailydocket-84053.appspot.com',
    iosBundleId: 'com.example.dailyDocket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmNEF1EkoNfGIO0C1nu927YQDFEmXo8u4',
    appId: '1:626777238610:web:ef356957b7fd2a6a8e038b',
    messagingSenderId: '626777238610',
    projectId: 'dailydocket-84053',
    authDomain: 'dailydocket-84053.firebaseapp.com',
    storageBucket: 'dailydocket-84053.appspot.com',
  );
}
